### ISSUE TITLE
Wall HP in Ashran, Icon locations in AV

### ISSUE THREAD

**Issue by JDH0986** [AcidWeb/REPorter#11]
Wall HP isn't correct in Ashran, it will end up showing -20%ish before a wall goes down.  Additionally while playing AV I'm standing in the East Frostwolf Tower but it shows me on the map as if I'm in the West.  It does this for other player icons as well.

![ss](https://user-images.githubusercontent.com/80657247/111093070-2bb3f500-84f5-11eb-891f-0e15176132e1.png)

**Comment by AcidWeb** [comment]
I presume you are talking about IoC.
I will fix gate life in next release.

AV nodes are moved a little on the map as they would be unreadable in original locations. It is not a bug.
