### ISSUE TITLE
EoTs nodes are not showing

### ISSUE THREAD

**Issue by shoaibali** [AcidWeb/REPorter#14]
![image](https://user-images.githubusercontent.com/180494/185743362-d415238d-7fa5-4f5e-b4e2-72ccfe6e8d0c.png)

When I do a /reload after the gates have opened the nodes appear. Sometimes the nodes  appear well before the gates open. It is mostly broken. I am not sure why.

**Comment by AcidWeb** [comment]
This is a long-standing issue. Cause currently elude me.

**Comment by shoaibali** [comment]
thank you for the response @AcidWeb , yes it has been there for a while. Interesting part is that it is intermittent too. Workaround for /reloading  after gates open seem to do the trick. Anything else I can do to help debug this? Maybe it just Blizzards API thats broken. 
Feel free to close this ticket if this is already a known issue.

**Comment by AcidWeb** [comment]
When working on EOTS support for Battleground Blitz Braw mode I might found the cause. Next release will tell if I was right.

**Comment by shoaibali** [comment]
Thanks for the heads up @AcidWeb , keen to know what was causing it to glitch.

**Comment by AcidWeb** [comment]
Addon was checking too soon if map is in rated mode. And map was initiated to handle nodes that are used in non-rated mode.
