### ISSUE TITLE
IOC Gate Health

### ISSUE THREAD

**Issue by Refizul** [AcidWeb/REPorter#16]
Hi. Can you maybe upgrade the IOC Gate Health variable to 2400000 because it reflects the ingame health a little better. Currently RePorter switches to 0% when there are about 3% gate health left. 

kk thx :)

**Comment by AcidWeb** [comment]
Thanks for report. I will tweak it in next release.

**Comment by AcidWeb** [comment]
... I forgot about this issue. Let me fix it quick.
