### ISSUE TITLE
WoW asks to disable addon 2.9.6

### ISSUE THREAD

**Issue by ingeniious** [AcidWeb/REPorter#17]
Thank you so much for this addon! I have used it over the years. 

WoW Interface has version 2.9.6 
Updated: 03-26-23 01:33 AM
https://www.wowinterface.com/downloads/info21089-REPorter-BattlegroundMap.html

When in dungeons it hides the hotkeys on bars 2 and 3 and makes some of them not usable, then WoW asks to disable to the addon.

Going to try this version you have on github, 2.9.3.

**Comment by AcidWeb** [comment]
Github also have 2.9.6.

You have taint issues in your UI and REPorter is wrongly reported as the source of these problems.

**Comment by ingeniious** [comment]
> Github also have 2.9.6.
> 
> You have taint issues in your UI and REPorter is wrongly reported as the source of these problems.

What are taint issues?  The only other addon I am running is Recount.

This time as soon as I entered a BG it says "REPorter has been blocked from an action only available to the Blizzard UI"

**Comment by AcidWeb** [comment]
This should be fixed in 2.9.7.
