### ISSUE TITLE
Support TWW newest BG, Deephaul Ravine

### ISSUE THREAD

**Issue by alexandersoto** [AcidWeb/REPorter#20]
Hi - thanks for the addon! It doesn't look like Deephaul Ravine (TWW's latest BG) is working in the app yet. What's needed to get that supported? Happy to help.

**Comment by AcidWeb** [comment]
My time to finally level a char and finish 11.0 update of the addons.

**Comment by alexandersoto** [comment]
Fair enough! Let me know if there's anything I can do to help.

**Comment by chang180** [comment]
Hi,

I found out that the new battleground, Deephaul Ravine, has the code 2345, and I was able to make the map appear in the game. I’ve already submitted a pull request with the changes, but I would appreciate it if you could take a look and provide any feedback on the configuration.

Thanks!
