### ISSUE TITLE
Map doesnt scale on frame resize

### ISSUE THREAD

**Issue by thesimonho** [AcidWeb/REPorter#4]
I find that the map is too large in some BGs, but when I resize the map frame the map itself doesnt rescale to match the frame dimensions.

I have also tried reducing the scale in the options but the frame doesnt resize to fit. When I manually resize the frame it only adjusts the right and bottom sides of the frame, leaving a gap on the top and left sides of the scaled down map

**Comment by AcidWeb** [comment]
Dragging + SHIFT will move map inside the frame.

https://imgur.com/Qq9jwhN
