### ISSUE TITLE
Getting constant error in bgs now

### ISSUE THREAD

**Issue by shadowx582** [AcidWeb/REPorter#5]
Message: Interface\AddOns\REPorter\REPorter.lua:499: attempt to index field '?' (a nil value)
Time: Wed Dec 12 04:37:29 2018
Count: 64
Stack: Interface\AddOns\REPorter\REPorter.lua:499: attempt to index field '?' (a nil value)
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574>
(tail call): ?
Interface\AddOns\REPorter\REPorter.lua:499: in function `PointParse'
Interface\AddOns\REPorter\REPorter.lua:810: in function <Interface\AddOns\REPorter\REPorter.lua:761>
[C]: ?
...AddOns\REPorter\Libs\AceBucket-3.0\AceBucket-3.0.lua:73: in function <...AddOns\REPorter\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
...AddOns\REPorter\Libs\AceBucket-3.0\AceBucket-3.0.lua:89: in function `func'
...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: <none>

**Comment by AcidWeb** [comment]
Not tested it on 8.1 yet. I should fix it in next 72h.
