### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dreamtheme** [AcidWeb/REPorter#6]
I got this error
784x REPorter\REPorter-2.2.1.lua:846: bad argument #1 to 'wipe' (table expected, got nil)
[C]: ?
REPorter\REPorter-2.2.1.lua:846: in function `OnPOIUpdate'
REPorter\REPorter-2.2.1.lua:757: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by AcidWeb** [comment]
On which BG?

**Comment by dreamtheme** [comment]
Seething Shore

**Comment by AcidWeb** [comment]
I can't replicate this. This error appeared on single SS or every time you play one?

**Comment by dreamtheme** [comment]
On a single rated SS so far

**Comment by AcidWeb** [comment]
I will hotfix that soon. Probably It will not fix map but at least it will not spam with lua errors.
