### ISSUE TITLE
Tower and other icons missing on battleground map

### ISSUE THREAD

**Issue by stamicvs** [AcidWeb/REPorter#7]
Hi Acidweb,

since the patch 8.1.5 update from WoW and the battleground changes some things are not working correctly in RePorter.
In Eye of the Storm and Deepwind Gorge the icons for the towers (Eye) and the icons for the mines (DWG) are missing from the map.
I've also notices that in Silvershard mines the calculation of how many mine carts have to be turned in is always showing 0.
Could you please check again?
I am using RePorter 2.3.0

Thank you very much!

**Comment by AcidWeb** [comment]
I will check it out.

**Comment by AcidWeb** [comment]
Found the cause. Fixing this will take some time.
